// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ComicEdge struct {
	Cursor string `json:"cursor"`
	Node   *Comic `json:"node"`
}

type EpisodeEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Episode `json:"node"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type SourceCreatePayload struct {
	Source    *Source      `json:"source"`
	UserError []*UserError `json:"userError"`
}

type SourceInput struct {
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
}

type UserError struct {
	Message string   `json:"message"`
	Field   []string `json:"field"`
}
