# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
- schema.graphql
exec:
  filename: generated/generated.go
model:
  filename: model/generated.go
resolver:
  filename: resolver/resolver.go
  type: Resolver
autobind:
  - github.com/bickyeric/arumba/model

models:
  ID:
    model: github.com/bickyeric/arumba/model.ID
  Timestamp:
    model: github.com/bickyeric/arumba/model.Timestamp
