version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - run:
          name: DOCKER
          command: docker version

      - run:
          name: SSH
          command: ssh -V
