version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - run:
          name: DOCKER
          command: DOCKER_HOST=ssh://bickyeric@52.187.38.226 docker ps

      - run:
          name: SSH
          command: ssh -V
