version: '3.7'

services:
  api:
    image: bickyeric/arumba:${VERSION}
    ports:
      - "1907:1907"
    secrets:
      - source: env-file
        target: /.env

secrets:
  env-file:
    external: true
    name: arumba-api
